### ISSUE TITLE
CountryGroup functionality missing USA

### ISSUE THREAD

**Issue by James-Hogan** [nz-mbie/mbie-r-package#6]
HI Eric, 

The ImportTS2 function is not including the USA as a separate country grouping.  RTE data, extracting from TRED using ImportTS2, is allocating the USA to the Other group classification.

Peter's suggestion: "CountryGrouped() has country names hard coded into it, and the list is necessarily non-comprehensive and has to be added to from time to time when new countries pop up.  Basically anything showing up grouped as “Other” shows a problematic unknown country – if it recognises all countries there will be no ‘Other’ (Eric, this is worth putting in its helpfile, and maybe also generating a warning “Country XXX wasn’t recognised” if there are any entries as ‘other’)?"

Cheers,
James

**Comment by HaizhenWu** [comment]
I found the problem was due to the list of “Countries” for  type “IVSweights” including "United States of America" but not “USA” before "United States of America" converting to "USA" when “shorten = TRUE”.

So I hard coded “USA” to "United States of America" at the early stage of the script, such that “USA” be recognized to "United States of America" and then shortened to “USA”.

I also added the following line to capture the list of “Other” countries
OtherCountries <- unique(x[!x %in% Countries])
then print a warning message
> table(CountryGroup(dtf$CV1))

Africa and Middle East              Australia                 Canada                  China                Germany                  Japan     Korea, Republic of                  Other
                  4812                   5048                   4912                   4326                   4934                   4708                   4246                  79770
      Rest of Americas           Rest of Asia         Rest of Europe        Rest of Oceania                     UK                    USA
                  4746                   4818                   4994                   3682                   5026                   4996
Warning message:
In CountryGroup(dtf$CV1) :
  Countries 'Bay of Plenty , Southland , Marlborough , West Coast , Hawke's Bay , Canterbury , Manawatu-Wanganui , Auckland , Otago , Nelson , Northland , Tasman , Gisborne , Waikato , Taranaki , Wellington' wasn’t recognised by the country groups and treated as 'other'!
If this is not appropriate, please contact maintainer of the package {mbie}!
when length of OtherCountries is greater than 0.

Can Ilkka peer review the update of package {mbie}  to v0.9.3? The relevant scripts are:
[cid:image001.png@01D0DA85.56DCA270]

The following codes show that the ImportTS2() output become normal after the updating.

> library(package = "mbie", lib.loc = "P:/R/libraries/AAA TEST LIBRARIES")

> library(mbieDBmisc)

> TRED <- odbcConnect("TRED_Prod")       # for accessing data from Infoshare etc

> dtf <- ImportTS2(TRED, "RTEs by Area, Type, Origin, Product")

Sending the following query to the database:



              SELECT

                TimePeriod,

                CV1, CV2, CV3, CV4, CV5, CV6, CV7, CV8,

                Value,

                Unit,

                Magnitude,

                Obs_Status

              FROM TRED.TimeSeries.GetDCPdataset

              WHERE Dataset_ID = 4373

Warning message:

In CountryGroup(OutData[, ColNames[[i]]], ...) :

  Countries 'Bay of Plenty , Southland , Marlborough , West Coast , Hawke's Bay , Canterbury , Manawatu-Wanganui , Auckland , Otago , Nelson , Northland , Tasman , Gisborne , Waikato , Taranaki , Wellington' wasn't recognised by the country groups and treated as 'other'!

 If this is not appropriate, please contact maintainer of the package {mbie}!

> table(dtf$CountryGrouped)



Africa and Middle East              Australia                 Canada                  China                Germany                  Japan

                  4812                   5048                   4912                   4326                   4934                   4708

    Korea, Republic of                  Other       Rest of Americas           Rest of Asia         Rest of Europe        Rest of Oceania

                  4246                  79770                   4746                   4818                   4994                   3682

                    UK                    USA

                  5026                   4996

Regards,
Eric

**Comment by HaizhenWu** [comment]
done and close.
